name: Content

on:
  workflow_dispatch:

jobs:
  content-update:
    name: Update Content
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the main repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          fetch-depth: 0

      - name: Checkout the secondary repo
        uses: actions/checkout@v3
        with:
          repository: 'static-frame/static-frame'
          path: 'static-frame'

