name: Content

on:
  workflow_dispatch:

jobs:
  content-update:
    name: Update Content
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout static-frame-www
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          fetch-depth: 0

      - name: Checkout static-frame
        uses: actions/checkout@v3
        with:
          repository: 'static-frame/static-frame'
          path: '../static-frame'

      - uses: actions/setup-python@master
        with:
          python-version: '3.11'

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test-3_11.txt
          export PYTHONPATH="${PYTHONPATH}:."
          python3 doc/build_json.py --write --output ../static-frame-www/site-static-frame/src/sf-api
        working-directory: ../static-frame
